name: Exploring Variables and Secrets

on:
  # push
  workflow_dispatch

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Docker Build
        run: docker build -t docker.io/${{ secrets.DOCKER_USERNAME }}/imageName:latest .

      - name: Docker Login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Docker Publish
        run: docker push docker.io/${{ secrets.DOCKER_USERNAME }}/imageName:latest

  deploy:
    needs: docker
    runs-on: ubuntu-latest
    steps:
      - name: Docker Run
        run: docker run -d -p 8080:80 docker.io/${{ secrets.DOCKER_USERNAME }}/imageName:latest

