name: Exploring Variables and Secrets

on:
  push

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: List files to check for Dockerfile
        run: ls -la
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag mynginx_image:$(date +%s)

        
      # - name: Debug - List Files
      #   run: ls -la

      # - name: Docker Build
      #   run: |
      #     echo docker build -t ${{ secrets.CONTAINER_REGISTRY }}/${{ secrets.DOCKER_USERNAME }}/mynginx_image:$(date +%s) .
      #     echo docker images 

      # - name: Docker Login
      #   run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin

      # - name: Docker Publish
      #   run: docker push ${{ secrets.CONTAINER_REGISTRY }}/${{ secrets.DOCKER_USERNAME }}/mynginx_image:$(date +%s)

  # deploy:
  #   needs: docker
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Docker Run
  #       run: docker run -d -p 8080:80 ${{ secrets.CONTAINER_REGISTRY }}/${{ secrets.DOCKER_USERNAME }}/mynginx_image:$(date +%s)

