name: Exploring Variables and Secrets

on:
  # push
  workflow_dispatch

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Debug - List Files
        run: ls -la

      - name: Docker Build
        run: echo docker build -t ${{ secrets.CONTAINER_REGISTRY }}/${{ secrets.DOCKER_USERNAME }}/mynginx_image:latest .

      - name: Docker Login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Docker Publish
        run: docker push ${{ secrets.CONTAINER_REGISTRY }}/${{ secrets.DOCKER_USERNAME }}/mynginx_image:latest

  deploy:
    needs: docker
    runs-on: ubuntu-latest
    steps:
      - name: Docker Run
        run: docker run -d -p 8080:80 ${{ secrets.CONTAINER_REGISTRY }}/${{ secrets.DOCKER_USERNAME }}/mynginx_image:latest

